### PR TITLE
Made a very basic 'Add User' dialog box

### PR DESCRIPTION
**Pull request by clarkritchie**
This is quite primitive, but I needed something functional to move forward.

### CODE REVIEW

**Comment by hharnisc** [comment]
Tried it out and it's not quite ready to be pushed to master.

Here's some notes:

**Add User Dialog**
adduser

**Add User Button**

adduserbutton

Another thing to think about, this only seems to cover the meteor base accounts package.  And doesn't work where all users a facebook/twitter/G+ etc.

**Comment by hharnisc** [comment]
I'm going to close this for now. When you've got some more changes I'll pull it and test it again.

**Comment by clarkritchie** [comment]
No worries, and thanks for the feedback.  How would you approach the use case for apps that don't support external authentication and don't permit self registration?  We don't do either, and thus need the standard functionality like adding users manually and resetting passwords.  Maybe that's a module within this that someone can optionally enable if they need to also do local user management as well as role management?

**Comment by hharnisc** [comment]
A couple of cases

**"accounts-password" installed in list of packages** 
- Some sort of feature detection <em>check package installed or a test at runtime -- not really sure about how to do this part</em>
- Show add user button
- Add user dialog has a couple of fields (need to parse the Accounts.UI.Config)
  - Optionally show email (must at least have email or username) <em>See http://docs.meteor.com/#accounts_ui_config</em>
  - Optionally show username (must at least have email or username) <em>See http://docs.meteor.com/#accounts_ui_config</em>
  - Password
  - Confirm password

If the "accounts-password" package is not installed I would hide the "Add User" button.

With mixed users it seems like it would be fine to have the option to add users so long as it was clear that the user type would be "accounts-password".

I'm sure there's some more cases here that need to be though through, but that might be good start. I think this should at least cover your case, as well as the case with mixed accounts.  I'll see if I can find anyone with a good way of detecting if packages are installed.

**Pull request closed without merging**
